name: Test Image Cache

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6
        with:
          version: 10
          cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Build action
        run: pnpm install && pnpm build

      - name: Cache Images
        uses: ./
        with:
          images: |
            ubuntu:24.04
            postgres:18
            alpine:latest
            golang:1.26
            swr.cn-north-4.myhuaweicloud.com/sanbei/chat:latest

      - name: Pull Images(这里应该会命中缓存)
        run: |
          docker pull ubuntu:24.04
          docker pull postgres:18
    